### ISSUE TITLE
Different Styles

### ISSUE THREAD

**Issue by adius** [rstacruz/hicat#5]
There should be the possibility to select different styles for highlighting.
Highlight.js seems to have quite a decent collection.
The hicat default theme is pretty lame in my opinion.

**Comment by rstacruz** [comment]
Thanks! I believe the world is 'color schemes' or 'themes' — and these are actually not in highlight.js's territory (we only use highlight to tokenize the code into keywords, strings, comments, etc).

**Comment by adius** [comment]
Highlight.js calls them styles and it seems to support quite a few of them …
https://highlightjs.org/static/demo
